disabled_rules:
  - line_length
  - identifier_name
  - todo
  - trailing_comma
opt_in_rules:
  - file_header
  - closure_end_indentation
included:
  - DroidKaigi 2020
excluded:
  - Carthage
  - Pods
file_header:
  severity: error
  forbidden_pattern: .
