# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'DroidKaigi 2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MaterialComponents'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for DroidKaigi 2020

  target 'DroidKaigi 2020Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DroidKaigi 2020UITests' do
    # Pods for testing
  end

end
