-keepnames class io.github.droidkaigi.confsched2020.model.SessionId
-keepnames class io.github.droidkaigi.confsched2020.session.ui.SessionDetailFragment
-keepnames class io.github.droidkaigi.confsched2020.session.ui.SessionsFragment