-keepnames class io.github.droidkaigi.confsched2020.model.SessionId
-keepnames class io.github.droidkaigi.confsched2020.session.ui.MainSessionsFragment
-keepnames class io.github.droidkaigi.confsched2020.session.ui.SessionDetailFragment
-keepnames class io.github.droidkaigi.confsched2020.staff.ui.StaffsFragment