#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "$@" 1>&2
    exit 1
}

if ! type travis >/dev/null 2>&1; then
    die "travis command is required"
fi

echo "Input a name of a secret"; read name
echo "Input a value of a secret"; read -s value

travis encrypt --com -i "$name=$value"