#!/usr/bin/env bash

set -euo pipefail

die() {
    echo "$@" 1>&2
    exit 1
}

if ! type travis >/dev/null 2>&1; then
    die "travis command is required"
fi

cd "$(git rev-parse --show-toplevel)"

zip -r to_be_encrypted.zip to_be_encrypted/
travis encrypt-file --com -i to_be_encrypted.zip
mv -f to_be_encrypted.zip.enc .encrypted/

echo; echo "You can ignore the message of Travis gem above"
echo "Run 'git add .encrypted/to_be_encrypted.zip.enc' and commit it."