on:
  - push

jobs:
  feature-deploy:
    runs-on: macOS-latest
    name: A job to build an staging android apk

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: .ci/bin/generate_gradle_cache_slug > .gradle-lock
    - uses: actions/cache@preview
      id: cache-android
      with:
        path: ${{ env.HOME }}/.android
        key: ${{ runner.os }}-android-${{ hashFiles('**/.gradle-lock') }}
        restore-keys: |
          ${{ runner.os }}-android-
    - uses: actions/cache@preview
      id: cache-home-gradle
      with:
        path: ${{ env.HOME }}/.gradle
        key: ${{ runner.os }}-home-gradle-${{ hashFiles('**/.gradle-lock') }}
        restore-keys: |
          ${{ runner.os }}-home-gradle-
    - uses: actions/cache@preview
      id: cache-gradle
      with:
        path: .gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle-lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@preview
      id: cache-m2
      with:
        path: ${{ env.HOME }}/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/.gradle-lock') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Install dependencies
      uses: ./.github/actions/android-gradle
      if: steps.cache-android.outputs.cache-hit != 'true' && steps.cache-home-gradle.outputs.cache-hit != 'true' && steps.cache-gradle.outputs.cache-hit != 'true' && steps.cache-m2.outputs.cache-hit != 'true'
      with:
        run: androidDependenciesExtra dependenciesExtra
      env:
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
    - uses: ./.github/actions/assemble-task-finder
      id: assemble-task-finder
      with:
        build_flavor: debug
    - uses: ./.github/actions/android-gradle
      with:
        run: ${{ steps.assemble-task-finder.outputs.args }} -PdisablePreDex
      env:
        GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'